default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bootybase

test:
  <<: *default
  database: bootybase

production:
  <<: *default
  database: bootybase
